### ISSUE TITLE
[BE] feat: 웹 훅 데이터를 활용한 커밋 처리 로직 구현

### ISSUE THREAD

**Issue by jusung-c** [DKU-Dgaja/gitudy#431]
## 어떤 기능인가요?
웹 훅 데이터를 활용한 커밋 처리 로직을 구현한다.

먼저 현재 웹 훅의 로직을 간단하게 살펴보면 다음과 같다.
<img width="444" alt="image" src="https://github.com/user-attachments/assets/eb67a9c6-e891-4e05-9fa6-9adf0eabdad5">

### 커밋 처리 로직 
웹훅 데이터 처리를 위해 구현할 로직은 다음과 같다.
<img width="565" alt="image" src="https://github.com/user-attachments/assets/179028ba-8a33-40d7-ab9b-678cd4485e1c">

> 해당 로직에 대한 고민과 답변은 [노션](https://believed-sherbet-deb.notion.site/MongoDB-c1a95892f78447799877ff7ec21af547?pvs=4)에서 확인할 수 있다. 

<br/>

**따라서 웹훅에서 데이터를 전송해 커밋을 처리할 API가 필요하다!!**

**필요한 정보(웹훅에서 파라미터로 건네줄 데이터)**
- commit 정보 (id(sha), message, username, timestamp)
- repository 정보 (fullname)

고민: 매개 변수가 너무 많아질 것 같은데 그냥 통으로 받는 게 나을까?

**API가 처리할 일**
1. 커밋 필터링
    1. 먼저 커밋 메세지가 컨벤션을 지키는지 판단한다.
    2. 이미 저장된 커밋은 아닌지 판단한다. → 웹훅이 알 수 없는 이유로 같은 커밋을 2번 보낼 가능성이 있는가?
2. 권한 검증
    1. 레포지토리 정보, 유저 정보를 통해 해당 스터디의 활동중인 회원인지 판단한다.
3. StudyCommit 및 TodoMapping 정보 업데이트
    1. 해당 커밋이 투두의 마감일을 지켰는지 판단한 후 그 결과에 따라 TodoMapping 정보를 업데이트한다.
    2. 레포지토리 정보, 유저와 커밋 메세지의 TODO 코드를 통해 어느 스터디의 어느 투두에 해당하는 커밋인지 특정한후 StudyCommit으로 저장한다.

**API의 반환 타입**
고민: 커밋이 올바르게 저장되었거나 어떠한 이유로 저장되지 않았음을, 즉 성공 여부를 웹훅 프로젝트에 알려야할까??

<br/>
오랜만의 feat이네요~ 

<br/>

**Comment by j-ra1n** [comment]
👍 👍

**Comment by ghdcksgml1** [comment]
> **api의 반환 타입 고민**
> 커밋이 올바르게 저장되었거나 어떠한 이유로 저장되지 않았음을 웹훅 프로젝트에 알려야할까?

void로 설정하고, **201 Created**로 내려주세용
