### ISSUE TITLE
[BE] feat: github api 사용 시 로그인한 사용자의 토큰을 사용하도록 로직 구현

### ISSUE THREAD

**Issue by jusung-c** [DKU-Dgaja/gitudy#444]
## 어떤 기능인가요?

github api를 사용해 레포지토리 생성, 레포지토리 초대 및 수락 등 권한(토큰)이 필요한 로직에 동적으로 로그인한 사용자의 토큰을 사용하도록 로직을 구현한다.

## 작업 상세 내용
- [ ] 기존의 설정파일을 통해 정적으로 토큰을 넣어주던 로직 제거
- [ ] 동적으로 토큰 넣어주기

**Comment by jusung-c** [comment]
### 공식문서 OAuth 토큰 관련 정보

<img width="500" alt="image" src="https://github.com/user-attachments/assets/bc1e3016-75a5-47e4-ad9b-bdf4b452cd2b">

- 1시간에 10번 이상 로그인해서 새로 토큰이 발급될 경우 재인증받도록 처리됨
- 1시간에 10번이 아니더라도 10개 이상의 토큰이 생기면 제일 오래된 토큰 삭제됨
- 보안상 1년동안 사용되지 않은 토큰은 자동으로 제거됨
- 깃허브 앱을 통한 인증의 경우 토큰에 만료기한도 설정되어 있고, refresh token도 발급받을 수 있으나 oauth 앱 인증을 통한 인증의 경우엔 기본적으로 만료기한이 없는 토큰이고, refresh token 관련 문서를 공식문서에서 찾을 수 없었음

**대신 토큰을 reset할 수 있는 방법을 찾았습니다.**

<img width="500" alt="image" src="https://github.com/user-attachments/assets/5a995b01-dcf3-48be-a337-aef032ea4458">

**토큰을 삭제할 수 있는 api도 존재합니다.**

<img width="500" alt="image" src="https://github.com/user-attachments/assets/d5d8fa47-26c1-478f-8857-a5e691258dea">

**그렇다면 만든 토큰이 10개가 넘어가거나 1년동안 사용하지 않는 경우 아니면 사실상 무제한 토큰이라는 뜻..?**

---

### 토큰 관련 테스트
공식문서에서 얻은 정보를 실제로 테스트해봤습니다.

1. 먼저 계속해서 로그인 토큰을 발급을 시도해봤습니다. 
    - 정확히 10번인지는 세보지 않았으나 어느정도 시도했을 때 권한을 재동의 받는 페이지로 잘 이동됐습니다.

2. 발급받은 토큰의 정보를 확인하는 api를 호출해봤습니다.
    <img width="500" alt="image" src="https://github.com/user-attachments/assets/3d473b31-8df0-4ddf-989a-97d85b95ecb4">

    - oauth 인증으로 발급받은 토큰은 expires_at이 null로 설정된 것을 보아 실제로 만료기한이 없는 무제한 토큰임을 확인했습니다.
    - repo 권한의 토큰임을 확인했습니다.

3. 발급받은 토큰으로 토큰 재설정 api를 호출해봤습니다.
    <img width="480" alt="image" src="https://github.com/user-attachments/assets/fd0292ee-55e0-41c1-9199-bbb3a18523bb">

    - 실제로 같은 repo 권한의 새로운 무제한 토큰이 발급되는 것을 확인했습니다. 

4. 재발급 이전의 토큰으로 다시 정보를 조회하는 api를 호출해봤습니다.
    <img width="480" alt="image" src="https://github.com/user-attachments/assets/fab3ed0d-9e7b-48a2-b41d-d7034e1f01c5">

    - 재발급을 받으면 기존의 토큰은 자동으로 삭제됨을 확인했습니다.
    - 재발급 받은 토큰으로는 정보 조회 api가 잘 호출됨을 확인했습니다.

5. 재발급 받은 토큰 삭제 api 호출
    - 토큰을 삭제한 후 토큰 정보를 조회하면 조회되지 않음을 확인했습니다. 

---

### 생각해본 토큰 관리 방법

**방법 1) 토큰은 어차피 로그인할때마다 새로 생성되고, 깃허브가 자동으로 10개까지 토큰을 관리해주니까 그대로 저장해서 사용하는 방법**

- 10개가 넘을 경우 자동으로 오래된 토큰이 삭제되고, 1시간 이내에 10번 이상 로그인할 경우 자동으로 권한을 다시 확인하도록 요청하므로 레디스에서 최신순으로 10개만 저장하고 나머지는 신경쓰지 않는 방법.
- 만약 사용하다가 만료된 토큰일 경우 토큰 재설정 api를 통해 토큰 업데이트 후 사용

<img width="727" alt="image" src="https://github.com/user-attachments/assets/ecb8e670-fa9d-4111-b68f-40209f75b235">

**방법 2) 자체적으로 토큰 개수 관리**

토큰의 개수를 자체적으로 지정한 개수만큼 저장해 사용할 때마다 레디스에 존재하는 토큰인지 판단한다. 개수를 넘어갈 경우 토큰 삭제 api를 통해 삭제해준다.

1번 방법과 로직은 거의 동일합니다.

--- 

토큰의 종류가 다양하고 토큰마다 api가 달라서 좀 헷갈리네요. 더 나은 방법이 있으면 알려주세요!
일단은 깃허브가 자동으로 관리해주는 방법 1로 진행하고 있겠습니다~

**Comment by jusung-c** [comment]
1. 레디스에 저장할 githubToken 레코드 클래스
    - @Id: token
    - @Indexed String githubId
        - 사용자 토큰 조회 시 필요
    - 무제한 토큰이므로 `timeToLive`는  따로 설정하지 않음

2. 토큰 관리 서비스
    - 토큰 조회 로직
        - githubId로 토큰 조회 후 가장 최신의 토큰 조회
    - 토큰 저장 로직
        - 로그인 후 얻은 토큰과 githubId를 이용해 저장
        - 저장 전 이미 10개의 토큰이 있을 경우 토큰 삭제 로직 먼저 호출
    - 토큰 삭제 로직
        - 먼저 가장 오래된 토큰의 정보를 호출
            - 정보가 존재할 경우: github token delete api 호출
                - 예외처리: 깃허브를 믿고 삭제 실패 시 로그찍고 넘어감
            - 정보가 존재하지 않을 경우: github가 자동으로 삭제해준 것
        - 가장 오래된 토큰을 삭제

**Comment by jusung-c** [comment]
생각해봤는데 그냥 사용자별로 최신의 토큰 하나만 저장해두고 사용하다가 만료되면 재발급해서 업데이트하는 게 나을 것 같네요

<img width="766" alt="image" src="https://github.com/user-attachments/assets/a2ed5c83-dc17-465d-8f70-c1886c9bba60">

**Comment by rndudals** [comment]
주성님 멋지시네요 👍👍🏻 만료 되면 새로 발급 받아서 하나씩만 저장해두는 식으로 하면 될 것 같아요! 거의 무제한 토큰이라 다행이네요!

**Comment by j-ra1n** [comment]
고생하십니다 😄😄 잘 정리해두면 매우 좋은 학습이 될 것 같습니다!!!
