### ISSUE TITLE
[BE] feat: 모니터링 환경 설정

### ISSUE THREAD

**Issue by jusung-c** [DKU-Dgaja/gitudy#499]
## 어떤 기능인가요?

- actuator 및 prometheus 의존성 추가
- actuator endpoint 시큐리티 설정
- application 환경 설정 수정

**Comment by j-ra1n** [comment]
오.. 고생하셨습니다 해당 설정으로 성능테스트도 가능하겠군요 👍 👍

**Comment by ghdcksgml1** [comment]
좋네요 포트 열려면 nginx 설정이 필요해서 말씀해주시면

8000번 외부포트로 포트포워딩해드릴게요.

도커 설정 후 연락주세용

**Comment by jusung-c** [comment]
배포 서버에 도커 설정 완료했습니다~

주소: http://gitudy.site:3000/d/ddunql43o7ytcb/gitudy-monitor?orgId=1&refresh=5s&from=now-30m&to=now
비밀번호는 톡으로 알려드릴게요!
